apiVersion: v1
kind: Service
metadata:
  labels:
    service: zookeeper
  name: zookeeper
spec:
  ports:
  - port: 2181
    targetPort: 2181
  selector:
    service: zookeeper
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: zookeeper
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      service: zookeeper
  template:
    metadata:
      labels:
        service: zookeeper
    spec:
      containers:
      - image: bitnami/zookeeper:latest
        name: zookeeper
        imagePullPolicy: Always
        env:
        - name: ALLOW_ANONYMOUS_LOGIN
          value: 'yes'

      restartPolicy: Always