apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-api-person-grpc
  name: udaconnect-api-person-grpc
spec:
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
  selector:
    service: udaconnect-api-person-grpc
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-api-person-grpc
  name: udaconnect-api-person-grpc
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-api-person-grpc
  template:
    metadata:
      labels:
        service: udaconnect-api-person-grpc
    spec:
      containers:
      - image: hungapp/udaconnect-api-person-grpc:lastest
        name: udaconnect-api-person-grpc
        imagePullPolicy: Always

      restartPolicy: Always