apiVersion: v1
kind: Service
metadata:
  labels:
    service: kafka
  name: kafka
spec:
  ports:
  - port: 9092
    targetPort: 9092
  selector:
    service: kafka
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: kafka
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      service: kafka
  template:
    metadata:
      labels:
        service: kafka
    spec:
      containers:
      - image: bitnami/kafka:latest
        name: kafka
        imagePullPolicy: Always
        env:
        - name: KAFKA_BROKER_ID
          value: '1'
        - name: KAFKA_LISTENERS
          value: 'PLAINTEXT://0.0.0.0:9092'
        - name: KAFKA_ADVERTISED_LISTENERS
          value: 'PLAINTEXT://kafka:9092'
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: 'zookeeper:2181'
        - name: ALLOW_PLAINTEXT_LISTENER
          value: 'yes'

      restartPolicy: Always